version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - export MAVEN_HOME=/opt/apache-maven-3.6.3
      - export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/apache-maven-3.6.3/bin
      - echo Build started on `date`
      - mvn compile
      - mvn package
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/techtest-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
