version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Entering install phase...
      - wget https://mirror.jframeworks.com/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      - tar xzvf apache-maven-3.6.3-bin.tar.gz -C /opt/
      - export PATH=/opt/apache-maven-3.6.3/bin:$PATH
      - export MAVEN_HOME=/opt/apache-maven-3.6.3
  build:
    commands:
      - echo Build started on `date`
      - echo $PATH
      - echo $MAVEN_HOME
      - ls /opt
      - hostname
      - ifconfig
      - mvn compile
      - mvn package
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/techtest-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
