version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Entering install phase...
  build:
    commands:
      - echo Build started on `date`
      - echo $PATH
      - echo $JAVA_HOME
      - echo $MAVEN_HOME
      - mvn compile
      - mvn package
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/techtest-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
